[package]
name = "that-sky-ahook"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
color-hook = { git = "https://github.com/flakes-ink/color-hook" }
libc = "0.2"
mlua = { version = "0.12", features = ["lua52"] }
jni = "0.22"
pollster = "0.4"
raw-window-handle = "0.6"
wgpu = "30.0.0"
egui = "0.36"
egui-wgpu = "0.36"

# Override release profile to not strip and to export init_hook
[profile.release]
strip = "none"
lto = true
